### ISSUE TITLE
Move over intro JAX lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#1]
Shift https://github.com/QuantEcon/lecture-python-programming.myst/blob/main/lectures/jax_intro.md to this repo

**Comment by mmcky** [comment]
I will migrate this on Monday when organising to go live.

**Comment by jstac** [comment]
@mmcky Please add this to the TOC after `about` --- https://github.com/QuantEcon/lecture-jax/pull/40/files#r1187011927
