### ISSUE TITLE
Add a lecture on optimal savings with discrete state-action DP

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#10]
Turn https://github.com/QuantEcon/cbc_workshops/blob/main/day_4/opt_savings_jax.ipynb into a JAX lecture

The background and equations for the problem can be found here:
https://github.com/QuantEcon/cbc_workshops/blob/main/day_3/opt_savings.ipynb

They should be merged in above (but the numba code should be omitted).

This lecture uses dynamic programming but the state and action are discrete, so there is no approximation issue and maximization is easy (brute force).

**Comment by jstac** [comment]
@chappiewuzefan , can you please take care of this one please

**Comment by chappiewuzefan** [comment]
Sure, I'm working on it

**Comment by jstac** [comment]
This issue will be closed by #23
