### ISSUE TITLE
remove extra function from opt savings

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#107]
In https://jax.quantecon.org/opt_savings.html it seems the function `create_consumption_model` can be deleted.

After it's deleted `create_consumption_model_jax` can be renamed to `create_consumption_model`.

CC @HumphreyYang @Smit-create

**Comment by jstac** [comment]
Can also be deleted: 
 
```
Model = namedtuple('Model',
                    ('β', 'R', 'γ', 'w_grid', 'y_grid', 'Q'))
```

**Comment by HumphreyYang** [comment]
Many thanks @jstac and @Smit-create,

I am working on this now.

**Comment by Smit-create** [comment]
Thanks, @jstac for reporting it. Thanks, @HumphreyYang for taking this up.
