### ISSUE TITLE
aiyagari lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#123]
Get rid of class, use namedtuple.

**Comment by shlff** [comment]
Hi @jstac the following lecture also uses dataclass:
- https://jax.quantecon.org/ifp_egm.html
- https://jax.quantecon.org/arellano.html

I suggest we use namedtuple instead of class there as well.

**Comment by jstac** [comment]
I agree @shlff .  Could you please open issues for these lectures?
