### ISSUE TITLE
inserted figures not rendered properly in downloaded notebooks and colab-launched notebooks

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-jax#139]
Hi @jstac and @mmcky , I noticed an issue while reviewing some PR this morning:

the inserted figures in the jax lectures are not rendered properly in either downloaded notebooks

<img width="1045" alt="Screenshot 2024-03-04 at 1 49 31 pm" src="https://github.com/QuantEcon/lecture-jax/assets/53931041/a2098602-df27-4a04-bc21-83ba22ddaa28">

or colab-launched notebooks:
<img width="1328" alt="Screenshot 2024-03-04 at 1 50 28 pm" src="https://github.com/QuantEcon/lecture-jax/assets/53931041/4104bedf-2232-4a49-bddd-45f9c53acd3b">

**Comment by mmcky** [comment]
thanks @shlff for reporting this.

**Comment by mmcky** [comment]
thansk @shlff the source has not been correctly setup to show those figures

```
![https://python-advanced.quantecon.org/_static/lecture_specific/arellano/arellano_bond_prices.png](https://python-advanced.quantecon.org/_static/lecture_specific/arellano/arellano_bond_prices.png)
```

I will fix this soon.

**Comment by jstac** [comment]
Thanks @shlff , good catch!!

Thanks for fixing @mmcky .  Let's publish again soon so this doesn't stay live.

**Comment by mmcky** [comment]
thanks @jstac I published this last night.

**Comment by jstac** [comment]
Thanks @mmcky :-)
