### ISSUE TITLE
no `Download Notebook` option

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-jax#140]
Hi @mmcky and @jstac , I just noticed that there is no `Download Notebook` option on the top right of the Jax lectures website:

https://jax.quantecon.org/intro.html

Are we intended to do that?

**Comment by mmcky** [comment]
thanks @shlff I will look into this.

**Comment by mmcky** [comment]
@shlff was this icon not present before?

<img width="46" alt="Screenshot 2024-03-07 at 12 40 14 pm" src="https://github.com/QuantEcon/lecture-jax/assets/8263752/76bf5d05-d1b5-4e29-aebd-9b71c00c5cb6">

Looks like this is now fixed. would you mind confirming on your end and then closing this issue?

**Comment by shlff** [comment]
Thanks @mmcky . I can confirm it, and it's great to see this feature back!

**Comment by shlff** [comment]
Hi @mmcky , sorry to bother you about this. But this `Download Notebook` option is weirdly missing again:

https://jax.quantecon.org/intro.html

**Comment by jstac** [comment]
Download notebooks is visible to me.  OK to close this @mmcky ?

**Comment by shlff** [comment]
Thanks @jstac, I checked this just now, and the "Download " icon is visible to me, too.
