### ISSUE TITLE
Add a common start to all lectures

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#24]
At the start of each lecture we typically have some preamble that checks if the GPU is in use --- see, e.g., https://6441331571e8322fca3f55c3--incomparable-parfait-2417f8.netlify.app/aiyagari_jax.html

It would be good to standardize this.  I suggest adding `!nvidia-smi` to show the GPU type as well.

As part of it, we need some kind of note informing people that we are building on a GPU, such as the one that @mmcky was been working on.

Perhaps all of this preamble should be read in from a file at the top of each lecture, so that we standardize it and make it easy to edit in one place?

@HengchengZhang , could you please work on this in collaboration with @mmcky ?

**Comment by mmcky** [comment]
https://manual.quantecon.org/styleguide/code.html#jax

**Comment by jstac** [comment]
Some of the lectures include code such as `print(jax.devices())`.  

That code should be unified with the common start --- removed from lectures and put in the file we're going to read from in the common start.

**Comment by jstac** [comment]
@mmcky can this be closed?

**Comment by mmcky** [comment]
>  I suggest adding !nvidia-smi to show the GPU type as well.

#60 addresses this comment as well
