### ISSUE TITLE
IFP using endogenous grid method

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#26]
Write  a version of https://python.quantecon.org/ifp.html that uses the endogenous grid method.

(See https://python.quantecon.org/ifp.html)

Check that the results are the same as in the original (w/o the endogeous grid method).

Then convert to JAX.

**Comment by jstac** [comment]
Hi @shlff --- this is essentially the same Numba code as the original lecture?

The task here is to convert this code to JAX.

**Comment by jstac** [comment]
I see.  Nice work @shlff .  This will be a very helpful step!

**Comment by jstac** [comment]
Nice work @shlff .  This looks very good.

Yes, it would be great if you could turn this into a PR.  In this case, there is no existing lecture that exactly matches it --- correct?  

Let's discuss it today.

**Comment by shlff** [comment]
Thanks for your nice and helpful comments @jstac . 

I've updated the contexts required for understanding the notebook. 

Please find it here:
- https://gist.github.com/shlff/4218ae71c0f47777bd079f8ef8565c6e

**Comment by jstac** [comment]
Nice work on this @shlff .  I'm looking forward to seeing the PR.
