### ISSUE TITLE
Move over part of Newton lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#3]
Move over the last part of https://python.quantecon.org/newton_method.html, which uses JAX

The JAX part starts from https://python.quantecon.org/newton_method.html#using-newtons-method

At the start of this new lecture, reference https://python.quantecon.org/newton_method.html and state that we are going to solve the problem using JAX.

Give a brief explanation of the problem, copied from https://python.quantecon.org/newton_method.html, at the start.

**Comment by HengchengZhang** [comment]
@jstac  Hi John, I'm working on this and could you please assign this issue#3 to me.

**Comment by jstac** [comment]
Done.  Thanks @HengchengZhang.  Please let me know if you have questions.  I can zoom or see you in the office this afternoon around 1 or 2pm.
