### ISSUE TITLE
remove jit from outer loop

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#33]
Remove jit of outer loop in wealth dynamics lecture.

```python
# Create the jit function
wealth_time_series_for_loop_jax = jax.jit(wealth_time_series_for_loop_jax,
                                          static_argnums=(1,3,))
```

Message: Compiling module jit_wealth_time_series_for_loop_jax] Very slow compile? 

There isn't much benefit compiling the outer loop and the cost is slow compilation.  Let's remove this.

**Comment by chappiewuzefan** [comment]
refer to #62
