### ISSUE TITLE
Items to Update for Going LIVE

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-jax#36]
I noticed a few items that need updating

The latest build using `quantecon docker` and latest `anaconda==2023.03`

https://6458429da0896444878ca406--incomparable-parfait-2417f8.netlify.app/intro.html

- [x] the `toc` currently uses `other` and should be renamed (https://6458429da0896444878ca406--incomparable-parfait-2417f8.netlify.app/intro.html)
- [x] the `kesten processes` lecture builds fine on `GitHub Actions` but requires GPU cards > 10Gb

The following error occurs on `quantecon-gpu-server1` with RTX 3080

```
/home/mmcky/work/lecture-jax/lectures/kesten_processes.md: Executing notebook using local CWD [mystnb]     
2023-05-08 10:31:44.531319: W external/xla/xla/service/hlo_rematerialization.cc:2194] Can't reduce memory use below 7.33GiB (7871741952 bytes) by rematerialization; only reduced to 9.32GiB (10004000016 bytes)
```

most of our users will be using these desktop cards so we should add a `note` admonition. 

cc: @jstac @HengchengZhang @HumphreyYang

**Comment by jstac** [comment]
Thanks @mmcky.

@HumphreyYang , as mentioned before regarding those lax.scan loops, I recommend we reduce the size of the simulation relative to the for loop version.  If we want to compare the timing, then the for loop version could be rerun at a smaller simulation size, and the lax.scan one run at the same small size.

**Comment by jstac** [comment]
@mmcky , FYI, I need to resolve #39 before going live.  I'll do that now.
