### ISSUE TITLE
Add a JAX version of the inventory lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#4]
Repeat the coding part of https://python.quantecon.org/inventory_dynamics.html but using JAX.

Reference https://python.quantecon.org/inventory_dynamics.html at the start, so the reader can see the original problem and where it comes from.

Start with the key equations and then redo the simulations in JAX.

Add another exercise that request some heavy computation,.

**Comment by HumphreyYang** [comment]
Hi team,

I can work on this if there is no one else on this right now :) 

Many thanks.

**Comment by jstac** [comment]
Thanks @HumphreyYang , please go ahead.
