### ISSUE TITLE
Add a JAX version of the entry/exit Kesten process lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#5]
Add a version of https://python.quantecon.org/kesten_processes.html but using JAX for the computations.

Cite the original lecture to minimize repetition but include the key equations, so the code can be compared to the mathematics.

Take out the JAX exercise and put it here.

**Comment by HumphreyYang** [comment]
Hi team, 

I am working on this if no one else is looking at this and use [#330](https://github.com/QuantEcon/lecture-python.myst/pull/330) to remove the GPU badge.
