### ISSUE TITLE
[hardware] Include nvidia-smi output in lectures

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-jax#51]
@jstac here is a preview of the `nvidia-smi` output

https://6458e26e627cb621dbb3499a--incomparable-parfait-2417f8.netlify.app/wealth_dynamics.html

Let me know if you would like to role this out more widely.

**Comment by mmcky** [comment]
Here is a screenshot:

<img width="827" alt="Screenshot 2023-05-09 at 9 30 18 am" src="https://user-images.githubusercontent.com/8263752/236958601-6bc8ea03-8a23-46c4-81bd-03bbe2d403a8.png">

In my mind it might be too much information. I think it might be best to include it on 

https://6458e26e627cb621dbb3499a--incomparable-parfait-2417f8.netlify.app/status.html

and then link to it in the admonition for "more info".

**Comment by jstac** [comment]
Many thanks @mmcky .

I kind of like it, actually.  My vote is to include it in each lecture.  But if you feel strongly the other way then I'm good with that.

**Comment by mmcky** [comment]
Great - I'll add it across the lectures.
