### ISSUE TITLE
Add a lecture on max likelihood estimation

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#56]
We could redo this discussion in JAX: https://python.quantecon.org/mle.html#mle-with-numerical-methods

We only need to do section 80.5.

First we can use automatic differentiation.  Then we can repeat with the exact derivatives, the same as the existing code, and check that we get the same results.

We can explain that automatic differentiation is easier, more efficient, and possible when the gradients can't be computed analytically.

@Smit-create , do you have time to look at this?

**Comment by Smit-create** [comment]
Sure, I'll look into it. Thanks @jstac
