### ISSUE TITLE
Add a JAX version of the wealth distribution lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#6]
Extract the JAX code from https://python.quantecon.org/wealth_dynamics.html and turn it into a new lecture.

Restore https://python.quantecon.org/wealth_dynamics.html to its original form (remove GPU badge)

Add JAX code for computing the Lorenz curve and Gini coefficient

**Comment by Smit-create** [comment]
Sure, will do that. Thanks
