### ISSUE TITLE
a potential small typo in lecture 4: an asset pricing problem

### ISSUE THREAD

**Issue by wendingliu** [QuantEcon/lecture-jax#73]
Below equation (4.20), H is defines as $H[i, j, k,i^{\prime}, j^{\prime}, k^{\prime}] = \beta \sum_\limits{i^{\prime}, j^{\prime}, k^{\prime}} \kappa[i, j, k] P[i, i^{\prime}] Q[j, j^{\prime}] R[k, k^{\prime}]$. According to the code, $H[i, j, k,i^{\prime}, j^{\prime}, k^{\prime}]  = \beta \kappa[i, j, k] P[i, i^{\prime}] Q[j, j^{\prime}] R[k, k^{\prime}]$, i.e. the summation is unneeded. And $\beta$ in (4.21) is also unneeded.

**Comment by Jingni0117** [comment]
Wending forgot to @jstac

**Comment by jstac** [comment]
Thanks @wendingliu !  (and thanks @Jingni0117  :-)

@HengchengZhang or @HumphreyYang , could you please fix this in a PR?
