### ISSUE TITLE
order issue with opt savings

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#84]
In the optimal savings lecture https://jax.quantecon.org/opt_savings.html, the function R_sigma is used (in `get_value`) before it is defined.

The order should be swapped.

There might be a similar issue with the optimal investment lecture

**Comment by jstac** [comment]
Assigning @Smit-create but anyone is welcome to take this on.

**Comment by Smit-create** [comment]
Thanks John. I have noticed a couple of small other issues which I'll fix soon.
