### ISSUE TITLE
Errors in JAX lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#89]
P.S. There are a couple of errors in the 7th Jax lecture I thought I should point out: an out-of-place code block in section 7.3 running the lax.scan implementation before it is defined and an incomplete prompt for exercise 7.2.

RA team, please hold off on making these changes.

**Comment by mmcky** [comment]
This error is really interesting

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
File <timed exec>:2

NameError: name 'wealth_time_series_scan_jax' is not defined
```

as it hasn't triggered failures in `jb` builds even with `-W` which triggers errors for warnings. 

I am wondering if it has something to do with the cell magic. As the remainder of the lecture executes.

**Comment by mmcky** [comment]
Actually `wealth_time_series_scan_jax` isn't defined anywhere. But still not sure why this doesn't fail execution.

**Comment by jstac** [comment]
@mmcky , do you know if we can close this now?  I seem to remember a fix being put in.

**Comment by jstac** [comment]
pinging @mmcky

**Comment by mmcky** [comment]
@jstac the CI is properly configured to catch execution errors so this can be closed

https://github.com/QuantEcon/lecture-jax/blob/a7b173aa1b217e77955b4789eff450c67e496303/.github/workflows/ci.yml#L71
