### ISSUE TITLE
Add lecture on optimal investment

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-jax#9]
Turn https://github.com/QuantEcon/cbc_workshops/blob/main/day_4/investment_jax.ipynb into a JAX lecture

The background and equations for the problem can be found here: https://github.com/QuantEcon/cbc_workshops/blob/main/day_3/investment.ipynb

They should be merged in above (but the numba code should be omitted).

This lecture uses dynamic programming but the state and action are discrete, so there is no approximation issue and maximization is easy (brute force).

**Comment by Smit-create** [comment]
@jstac @mmcky I don't have permission to create a branch and push commits. Can you please provide access? Many thanks.

**Comment by jstac** [comment]
Sorry @Smit-create, my mistake!  I've fixed your permissions.
